---
name: Feature Request
description: Suggest a new feature or improvement for AgenticChat
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make AgenticChat better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe what you'd like to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - UI/UX
        - Chat / Prompting
        - Code Execution / Sandbox
        - Security
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Important
        - Critical - blocking my use case

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, links, or anything else that helps explain the feature.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: I am willing to contribute a PR for this feature
